class Errors():
    class RangeError(Exception):
        pass