class Errors():
    class RangeError(Exception):
        pass
    class AsyncError(Exception):
        pass